### ISSUE TITLE
At least 2 phrases are never translated

### ISSUE THREAD

**Issue by kaittodesk** [unlayer/translations#40]
I have found two phrases that do not get translated in any of the available languages - "Blocks" and "Search".

Here's an example in Russian language:
![unlayer_missing_phrases](https://user-images.githubusercontent.com/6755852/63246726-fb9a6680-c26b-11e9-9b4a-4a40ad5c4d0c.png)

Are these phrases missing from the translation files or is there an issue on the editor side?

**Comment by adeelraza** [comment]
@kaittodesk feel free to submit the translation for the missing keywords.

**Comment by kaittodesk** [comment]
I think you did not quite understand the issue.

The problem is that "Blocks" and "Search" translations already exist in the `ru.json` file, but they are not used by the Unlayer editor:
```json
{
  "labels.search": "Поиск",
  "tools.tabs.blocks": "Блоки"
}
```

It looks to me like Unlayer editor uses keys other than `tools.tabs.blocks` and `labels.search` for translation mapping.

PS. I am not sure `labels.search` is the correct key for search field placeholder translation.

**Comment by kaittodesk** [comment]
Looks like this issue has been resolved. "Blocks" translations is now applied and search input has been removed from the UI.
