### ISSUE TITLE
Forgotten translations

### ISSUE THREAD

**Issue by MaximeZumstein** [unlayer/translations#42]
Hi,

I found two new components not translated : 
First, all the aria-label of the text editor tools aren't translated (Like "Bullet list") and there are no key for them.
![Unlayer-text-editor](https://user-images.githubusercontent.com/44274585/63764621-83651e00-c8c7-11e9-978b-a0f703b32c5a.png)

The second one is the popup to add an URL link : 
![builder-no-translations](https://user-images.githubusercontent.com/44274585/63764772-d63ed580-c8c7-11e9-801d-53b67ec92e38.png)
All the form fields aren't translated and the title of the popup too.

**Comment by adeelraza** [comment]
@MaximeZumstein this has been resolved. Can you clear cache and try now?

**Comment by MaximeZumstein** [comment]
Thank you a lot, it's perfect !
