### ISSUE TITLE
Cannot translate text

### ISSUE THREAD

**Issue by gerardtoko** [unlayer/translations#6]
Hi,

I have need help for translate my application in french, Cannot translate this test
![screen shot 2018-04-13 at 11 33 37](https://user-images.githubusercontent.com/2236437/38727957-bc314e1e-3f0e-11e8-96e0-8c0057d0a3d2.png)

No present in json file translation.

Thanks for your help !

Good application and plugin.

**Comment by adeelraza** [comment]
@gerardtoko this missing translation has been added. Thank you.
